// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zitwgspfgaegedllipyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppdHdnc3BmZ2FlZ2VkbGxpcHljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNzQyMjksImV4cCI6MjA3Mzk1MDIyOX0.KVwa96noQ0CrtpSnrwkWEx9vcTGIZHY6lhlQsMqp30g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});